"""
evaluate_rag.py
===============
Step 3 of the evaluation pipeline.
Runs synthetic queries through the RAG retrieval pipeline
and calculates Precision@K, Recall@K, F1@K, and MRR.
Saves detailed results to JSON and summary to CSV.
"""

import os
import json
import csv
from dotenv import load_dotenv
from langchain_chroma import Chroma
from langchain_huggingface import HuggingFaceEmbeddings

load_dotenv()

current_dir = os.path.dirname(os.path.abspath(__file__))

# ─────────────────────────────────────────────
# STEP 1: Load the evaluation dataset
# ─────────────────────────────────────────────
# This is the file generated by generate_queries.py
# It contains 8 papers × 3 queries = 24 queries
# Each query has a known correct paper DOI

eval_file = os.path.join(current_dir, "eval_dataset.json")
with open(eval_file, "r", encoding="utf-8") as f:
    eval_dataset = json.load(f)

print(f"✅ Loaded {len(eval_dataset)} papers with queries")

# ─────────────────────────────────────────────
# STEP 2: Load the Chroma DB and embedding model
# ─────────────────────────────────────────────
# We use the same DB and embedding model as the RAG pipeline
# IMPORTANT: must be the same model used to BUILD the DB
# otherwise the vectors won't match

print("📂 Loading Chroma DB...")
db_dir = os.path.join(current_dir, "..", "Normal_RAG", "db", "chroma_db")
embeddings = HuggingFaceEmbeddings(model_name="all-MiniLM-L6-v2")
db = Chroma(persist_directory=db_dir, embedding_function=embeddings)
print("✅ DB loaded")

# ─────────────────────────────────────────────
# STEP 3: Define K and the retriever
# ─────────────────────────────────────────────
# K = how many facts to retrieve per query
# We use MMR to get diverse results (same as query_rag.py)

K = 3
retriever = db.as_retriever(
    search_type="mmr",
    search_kwargs={"k": K, "fetch_k": 20}
)

# ─────────────────────────────────────────────
# STEP 4: Define metric functions
# ─────────────────────────────────────────────

def precision_at_k(retrieved_dois: list, correct_doi: str, k: int) -> float:
    """
    Precision@K = number of relevant results in top K / K
    
    A retrieved fact is "relevant" if its DOI matches the correct paper's DOI.
    Example: if 2 out of 3 retrieved facts match → Precision@3 = 2/3 = 0.667
    """
    retrieved_k = retrieved_dois[:k]
    relevant = sum(1 for doi in retrieved_k if correct_doi in doi)
    return relevant / k


def recall_at_k(retrieved_dois: list, correct_doi: str, k: int, total_relevant: int) -> float:
    """
    Recall@K = number of relevant results in top K / total relevant in DB
    
    total_relevant = how many facts for this paper exist in the DB (facts_in_cskg)
    Example: if we retrieved 2 relevant facts but paper has 7 facts total → Recall@3 = 2/7 = 0.286
    """
    if total_relevant == 0:
        return 0.0
    retrieved_k = retrieved_dois[:k]
    relevant = sum(1 for doi in retrieved_k if correct_doi in doi)
    return relevant / total_relevant


def f1_score(precision: float, recall: float) -> float:
    """
    F1 = harmonic mean of Precision and Recall
    
    It balances both metrics into one number.
    If either precision or recall is 0, F1 is 0.
    Formula: 2 * (P * R) / (P + R)
    """
    if precision + recall == 0:
        return 0.0
    return 2 * (precision * recall) / (precision + recall)


def reciprocal_rank(retrieved_dois: list, correct_doi: str) -> float:
    """
    Reciprocal Rank = 1 / position of first relevant result
    
    If first relevant result is at position 1 → RR = 1/1 = 1.0
    If first relevant result is at position 2 → RR = 1/2 = 0.5
    If first relevant result is at position 3 → RR = 1/3 = 0.33
    If no relevant result found → RR = 0.0
    
    MRR is the Mean of RR across all queries.
    """
    for i, doi in enumerate(retrieved_dois):
        if correct_doi in doi:
            return 1.0 / (i + 1)  # +1 because positions start at 1 not 0
    return 0.0

# ─────────────────────────────────────────────
# STEP 5: Run evaluation
# ─────────────────────────────────────────────

print(f"\n🔍 Running evaluation with K={K}...")
print(f"   Total queries to evaluate: {sum(len(p['generated_queries']) for p in eval_dataset)}\n")

all_results = []      # detailed results for JSON
summary_rows = []     # flat rows for CSV

# Track overall metrics
all_precisions = []
all_recalls = []
all_f1s = []
all_rrs = []

for paper in eval_dataset:
    correct_doi = paper["doi"]
    total_relevant = paper["facts_in_cskg"]
    
    print(f"📄 Paper: {paper['title'][:50]}...")
    print(f"   Correct DOI: {correct_doi}")
    print(f"   Facts in DB: {total_relevant}")
    
    paper_results = []
    
    for query in paper["generated_queries"]:
        # Run query through RAG retriever
        retrieved_docs = retriever.invoke(query)
        
        # Extract DOIs from retrieved facts
        # Each fact looks like: "... (supported by X papers, source: https://doi.org/...)"
        retrieved_dois = []
        for doc in retrieved_docs:
            content = doc.page_content
            if "source:" in content:
                doi = content.split("source:")[-1].strip().rstrip(")")
                retrieved_dois.append(doi)
            else:
                retrieved_dois.append("")
        
        # Calculate metrics
        p = precision_at_k(retrieved_dois, correct_doi, K)
        r = recall_at_k(retrieved_dois, correct_doi, K, total_relevant)
        f1 = f1_score(p, r)
        rr = reciprocal_rank(retrieved_dois, correct_doi)
        
        # Store for averaging
        all_precisions.append(p)
        all_recalls.append(r)
        all_f1s.append(f1)
        all_rrs.append(rr)
        
        print(f"\n   Query: {query}")
        print(f"   Retrieved DOIs: {retrieved_dois}")
        print(f"   P@{K}={p:.3f} | R@{K}={r:.3f} | F1={f1:.3f} | RR={rr:.3f}")
        
        # Save detailed result
        query_result = {
            "query": query,
            "correct_doi": correct_doi,
            "retrieved_dois": retrieved_dois,
            "precision_at_k": p,
            "recall_at_k": r,
            "f1": f1,
            "reciprocal_rank": rr
        }
        paper_results.append(query_result)
        
        # Save CSV row
        summary_rows.append({
            "paper_title": paper["title"][:50],
            "query": query,
            "precision_at_k": round(p, 3),
            "recall_at_k": round(r, 3),
            "f1": round(f1, 3),
            "reciprocal_rank": round(rr, 3)
        })
    
    all_results.append({
        "paper": paper["title"],
        "doi": correct_doi,
        "queries": paper_results
    })
    print()

# ─────────────────────────────────────────────
# STEP 6: Calculate overall metrics
# ─────────────────────────────────────────────

mean_precision = sum(all_precisions) / len(all_precisions)
mean_recall = sum(all_recalls) / len(all_recalls)
mean_f1 = sum(all_f1s) / len(all_f1s)
mrr = sum(all_rrs) / len(all_rrs)

print("=" * 50)
print(f"📊 OVERALL RESULTS (K={K})")
print("=" * 50)
print(f"   Mean Precision@{K}: {mean_precision:.3f}")
print(f"   Mean Recall@{K}:    {mean_recall:.3f}")
print(f"   Mean F1@{K}:        {mean_f1:.3f}")
print(f"   MRR:               {mrr:.3f}")
print("=" * 50)

# ─────────────────────────────────────────────
# STEP 7: Save results
# ─────────────────────────────────────────────

# Add overall metrics to JSON
output = {
    "k": K,
    "overall_metrics": {
        "mean_precision_at_k": round(mean_precision, 3),
        "mean_recall_at_k": round(mean_recall, 3),
        "mean_f1_at_k": round(mean_f1, 3),
        "mrr": round(mrr, 3)
    },
    "per_paper_results": all_results
}

json_file = os.path.join(current_dir, "rag_eval_results.json")
with open(json_file, "w", encoding="utf-8") as f:
    json.dump(output, f, indent=2, ensure_ascii=False)

# Save CSV
csv_file = os.path.join(current_dir, "rag_eval_results.csv")
with open(csv_file, "w", newline="", encoding="utf-8") as f:
    writer = csv.DictWriter(f, fieldnames=["paper_title", "query", "precision_at_k", "recall_at_k", "f1", "reciprocal_rank"])
    writer.writeheader()
    writer.writerows(summary_rows)
    # Add overall summary row
    writer.writerow({
        "paper_title": "OVERALL",
        "query": "MEAN",
        "precision_at_k": round(mean_precision, 3),
        "recall_at_k": round(mean_recall, 3),
        "f1": round(mean_f1, 3),
        "reciprocal_rank": round(mrr, 3)
    })

print(f"\n✨ Detailed results saved to: rag_eval_results.json")
print(f"✨ Summary saved to: rag_eval_results.csv")